import type { Logger } from '@gamedev-agent/logging';
import type { Disposable, Timestamp } from '@gamedev-agent/shared';
import { CommandRunner } from './CommandRunner';
import type { ProcessHandle, ProcessHandleCallbacks } from './ProcessHandle';
import { TerminalProcessNotFoundError } from './TerminalErrors';
import type {
  SpawnedProcess,
  TerminalCommandResult,
  TerminalProcessId,
  TerminalProcessInfo,
  TerminalProcessRunner,
  TerminalRunOptions,
} from './TerminalTypes';

/** Options for constructing the {@link ProcessManager}. */
export interface ProcessManagerOptions {
  readonly runner: TerminalProcessRunner;
  readonly logger: Logger;
  readonly baseEnv?: Readonly<Record<string, string>>;
  readonly killGraceMs?: number;
}

/**
 * The registry and lifecycle owner for terminal processes.
 *
 * It composes the {@link CommandRunner}, tracks every live (and recently
 * finished) {@link ProcessHandle} by id, and exposes the three process
 * operations the Terminal Tool surfaces: `run` (foreground, resolves with the
 * full result), `start` (background, returns immediately with a process id),
 * and `stop` (cancel). The manager is the only place that maps a process id to
 * a handle, so lookups fail fast with a {@link TerminalProcessNotFoundError}.
 *
 * Process ids are generated by the caller (the {@link TerminalClient}) so the
 * same id flows through audit, events, and handle registry.
 */
export class ProcessManager implements Disposable {
  private static readonly MAX_HANDLES = 256;

  private readonly runner: CommandRunner;
  private readonly baseEnv: Readonly<Record<string, string>>;
  private readonly handles = new Map<string, ProcessHandle>();
  private disposed = false;

  constructor(options: ProcessManagerOptions) {
    this.baseEnv = options.baseEnv ?? {};
    this.runner = new CommandRunner(options.runner, options.logger, options.killGraceMs ?? 2000);
  }

  /**
   * Run a command in the foreground. Resolves with the captured result once the
   * process exits (or is killed by timeout/stop). The supplied `callbacks`
   * publish streaming output and completion events.
   */
  async run(
    processId: TerminalProcessId,
    options: TerminalRunOptions,
    callbacks: ProcessHandleCallbacks,
  ): Promise<TerminalCommandResult> {
    const handle = this.create(processId, options, callbacks);
    return handle.wait();
  }

  /**
   * Start a command in the background. Returns immediately with the process id
   * and metadata. Output streams via `callbacks`; completion fires
   * `callbacks.onExit` and the client publishes `terminal.command-completed`.
   */
  start(
    processId: TerminalProcessId,
    options: TerminalRunOptions,
    callbacks: ProcessHandleCallbacks,
  ): TerminalProcessInfo {
    const handle = this.create(processId, options, callbacks);
    return handle.info();
  }

  /** Stop (cancel) a running process by id. Returns its final info. */
  stop(processId: TerminalProcessId, signal = 'SIGTERM'): TerminalProcessInfo {
    const handle = this.require(processId);
    handle.kill(signal);
    return handle.info();
  }

  /** Snapshot of a single process by id. */
  get(processId: TerminalProcessId): TerminalProcessInfo {
    return this.require(processId).info();
  }

  /** All known processes (running and recently finished). */
  list(): ReadonlyArray<TerminalProcessInfo> {
    return [...this.handles.values()].map((handle) => handle.info());
  }

  /** Captured stdout/stderr for a process id. */
  output(processId: TerminalProcessId): { readonly stdout: string; readonly stderr: string } {
    return this.require(processId).output();
  }

  dispose(): void {
    if (this.disposed) {
      return;
    }
    this.disposed = true;
    for (const handle of this.handles.values()) {
      handle.dispose();
    }
    this.handles.clear();
  }

  // --- internals -------------------------------------------------------------

  private create(
    processId: TerminalProcessId,
    options: TerminalRunOptions,
    callbacks: ProcessHandleCallbacks,
  ): ProcessHandle {
    const handle = this.runner.spawn(
      processId,
      { ...options, background: options.background === true },
      callbacks,
      this.baseEnv,
    );
    this.handles.set(processId, handle);
    // Bound memory: once a process finishes it stays resolvable (so output can be
    // retrieved by id) until evicted when the registry exceeds MAX_HANDLES. We
    // evict the oldest finished handle first, never a still-running one.
    void handle
      .wait()
      .then(() => this.evictIfNeeded())
      .catch(() => {});
    return handle;
  }

  private evictIfNeeded(): void {
    if (this.handles.size <= ProcessManager.MAX_HANDLES) {
      return;
    }
    const finished = [...this.handles.entries()].filter(([, h]) => h.info().running === false);
    for (const [id] of finished) {
      if (this.handles.size <= ProcessManager.MAX_HANDLES) {
        break;
      }
      this.handles.delete(id);
    }
  }

  private require(processId: TerminalProcessId): ProcessHandle {
    const handle = this.handles.get(processId);
    if (handle === undefined) {
      throw new TerminalProcessNotFoundError(processId);
    }
    return handle;
  }
}

// Re-export for callers that build a fake backend directly.
export type { SpawnedProcess, Timestamp };
