import type { ModelInfo } from '../types';

export const BUILTIN_MODELS: readonly ModelInfo[] = [
  // ─── OpenAI ──────────────────────────────────────────────────────────────
  {
    id: 'gpt-4o',
    provider: 'openai',
    displayName: 'GPT-4o',
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    capabilities: ['chat', 'streaming', 'tool_calling', 'structured_output', 'vision', 'json_mode', 'parallel_tool_calls'],
    pricing: { promptPerMillion: 2.50, completionPerMillion: 10.00, currency: 'USD' },
  },
  {
    id: 'gpt-4o-mini',
    provider: 'openai',
    displayName: 'GPT-4o Mini',
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    capabilities: ['chat', 'streaming', 'tool_calling', 'structured_output', 'vision', 'json_mode', 'parallel_tool_calls'],
    pricing: { promptPerMillion: 0.15, completionPerMillion: 0.60, currency: 'USD' },
  },
  {
    id: 'o1',
    provider: 'openai',
    displayName: 'o1',
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    capabilities: ['chat', 'tool_calling', 'structured_output', 'json_mode'],
    pricing: { promptPerMillion: 15.00, completionPerMillion: 60.00, currency: 'USD' },
  },
  {
    id: 'o3-mini',
    provider: 'openai',
    displayName: 'o3 Mini',
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    capabilities: ['chat', 'tool_calling', 'structured_output', 'json_mode'],
    pricing: { promptPerMillion: 1.10, completionPerMillion: 4.40, currency: 'USD' },
  },
  // ─── Anthropic ───────────────────────────────────────────────────────────
  {
    id: 'claude-sonnet-4-20250514',
    provider: 'anthropic',
    displayName: 'Claude Sonnet 4',
    contextWindow: 200_000,
    maxOutputTokens: 8_192,
    capabilities: ['chat', 'streaming', 'tool_calling', 'structured_output', 'vision'],
    pricing: { promptPerMillion: 3.00, completionPerMillion: 15.00, currency: 'USD' },
  },
  {
    id: 'claude-haiku-3-5-20241022',
    provider: 'anthropic',
    displayName: 'Claude Haiku 3.5',
    contextWindow: 200_000,
    maxOutputTokens: 8_192,
    capabilities: ['chat', 'streaming', 'tool_calling', 'structured_output', 'vision'],
    pricing: { promptPerMillion: 0.80, completionPerMillion: 4.00, currency: 'USD' },
  },
  // ─── Google Gemini ───────────────────────────────────────────────────────
  {
    id: 'gemini-2.5-flash',
    provider: 'gemini',
    displayName: 'Gemini 2.5 Flash',
    contextWindow: 1_048_576,
    maxOutputTokens: 8_192,
    capabilities: ['chat', 'streaming', 'tool_calling', 'structured_output', 'vision', 'json_mode'],
    pricing: { promptPerMillion: 0.15, completionPerMillion: 0.60, currency: 'USD' },
  },
  {
    id: 'gemini-2.5-pro',
    provider: 'gemini',
    displayName: 'Gemini 2.5 Pro',
    contextWindow: 1_048_576,
    maxOutputTokens: 8_192,
    capabilities: ['chat', 'streaming', 'tool_calling', 'structured_output', 'vision', 'json_mode'],
    pricing: { promptPerMillion: 1.25, completionPerMillion: 5.00, currency: 'USD' },
  },
  // ─── DeepSeek ────────────────────────────────────────────────────────────
  {
    id: 'deepseek-chat',
    provider: 'deepseek',
    displayName: 'DeepSeek Chat (V3)',
    contextWindow: 64_000,
    maxOutputTokens: 8_192,
    capabilities: ['chat', 'streaming', 'tool_calling', 'json_mode'],
    pricing: { promptPerMillion: 0.27, completionPerMillion: 1.10, currency: 'USD' },
  },
  {
    id: 'deepseek-reasoner',
    provider: 'deepseek',
    displayName: 'DeepSeek Reasoner (R1)',
    contextWindow: 64_000,
    maxOutputTokens: 8_192,
    capabilities: ['chat', 'streaming', 'tool_calling', 'json_mode'],
    pricing: { promptPerMillion: 0.55, completionPerMillion: 2.19, currency: 'USD' },
  },
  // ─── OpenRouter ──────────────────────────────────────────────────────────
  {
    id: 'openrouter/auto',
    provider: 'openrouter',
    displayName: 'OpenRouter Auto',
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    capabilities: ['chat', 'streaming', 'tool_calling', 'structured_output', 'vision'],
    pricing: { promptPerMillion: 0, completionPerMillion: 0, currency: 'USD' },
  },
  {
    id: 'openai/gpt-4o-mini',
    provider: 'openrouter',
    displayName: 'GPT-4o Mini (via OpenRouter)',
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    capabilities: ['chat', 'streaming', 'tool_calling', 'structured_output', 'vision', 'json_mode', 'parallel_tool_calls'],
    pricing: { promptPerMillion: 0.15, completionPerMillion: 0.60, currency: 'USD' },
  },
  {
    id: 'meta-llama/llama-3.1-8b-instruct',
    provider: 'openrouter',
    displayName: 'Llama 3.1 8B Instruct (via OpenRouter)',
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    capabilities: ['chat', 'streaming', 'tool_calling'],
    pricing: { promptPerMillion: 0.055, completionPerMillion: 0.055, currency: 'USD' },
  },
  {
    id: 'google/gemini-2.0-flash-lite-preview-02-05',
    provider: 'openrouter',
    displayName: 'Gemini 2.0 Flash Lite (via OpenRouter)',
    contextWindow: 1_048_576,
    maxOutputTokens: 8_192,
    capabilities: ['chat', 'streaming', 'tool_calling', 'structured_output', 'vision', 'json_mode'],
    pricing: { promptPerMillion: 0.075, completionPerMillion: 0.30, currency: 'USD' },
  },
  // ─── Ollama ──────────────────────────────────────────────────────────────
  {
    id: 'ollama/llama3.1',
    provider: 'ollama',
    displayName: 'Llama 3.1 (local)',
    contextWindow: 8_192,
    maxOutputTokens: 4_096,
    capabilities: ['chat', 'streaming', 'tool_calling', 'json_mode'],
    pricing: { promptPerMillion: 0, completionPerMillion: 0, currency: 'USD' },
  },
  {
    id: 'ollama/qwen2.5',
    provider: 'ollama',
    displayName: 'Qwen 2.5 (local)',
    contextWindow: 32_768,
    maxOutputTokens: 8_192,
    capabilities: ['chat', 'streaming', 'tool_calling', 'json_mode'],
    pricing: { promptPerMillion: 0, completionPerMillion: 0, currency: 'USD' },
  },
];
